### ISSUE TITLE
Epub2NcxException/Epub3NavException exceptions are thrown when OPF and navigation files are located in different subdirectories

### ISSUE THREAD

**Issue by majora2007** [vers-one/EpubReader#91]
I'm getting the following exception on `book.GetNavigationAsync()`

```
VersOne.Epub.Epub3NavException: Incorrect EPUB 3 navigation document: target for anchor href "titlepage.xhtml" not found in EPUB manifest.
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef, Epub3NavOl epub3NavOl, String epub3NavigationBaseDirectoryPath)
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef, Epub3Nav epub3Nav, String epub3NavDocumentFilePath)
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef, Epub3NavDocument epub3NavDocument)
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef)
   at VersOne.Epub.EpubBookRef.<GetNavigationAsync>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at VersOne.Epub.EpubBookRef.GetNavigationAsync()
   at API.Services.BookService.GenerateTableOfContents(Chapter chapter) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 914
   ```
   
I can confirm this book was working correctly in the previous version. 

here are some parts of the epub. (I can send it to you outside of Github, you can contact me by grabbing my email from my git signature)

```
<item id="titlepage" href="Text/titlepage.xhtml" media-type="application/xhtml+xml" properties="svg calibre:title-page"/>
    <item id="toc.xhtml" href="Text/toc.xhtml" media-type="application/xhtml+xml" properties="nav"/>
```
```
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head>
    <meta name="dtb:uid" content="9781718349490"/>
    <meta name="dtb:depth" content="1"/>
    <meta name="dtb:totalPageCount" content="0"/>
    <meta name="dtb:maxPageNumber" content="0"/>
  </head>
<docTitle>
  <text>Peddler in Another World: I Can Go Back to My World Whenever I Want! Volume 1</text>
</docTitle>
<navMap>
  <navPoint id="navPoint1">
    <navLabel>
      <text>Cover</text>
    </navLabel>
    <content src="Text/titlepage.xhtml"/>
  </navPoint>
```
root/OEBPS/content.opf, 
root/OEBPS/toc.ncx
root/OEBPS/Text/all xhtml here

**Comment by vers-one** [comment]
Reproduced. Working on the fix.

**Comment by vers-one** [comment]
Turns out, this issue was present in EpubReader from its first release. Version 3.3.0 just added a sanity check which exposed this bug while previous versions were silently skipping all affected navigation items.

**Comment by majora2007** [comment]
Ahh interesting, I'm open to allowing silently failing if I pass a parameter in. In my code, I have validation checks as well.

**Comment by vers-one** [comment]
I'll publish a proper fix tomorrow.

**Comment by vers-one** [comment]
Fixed in version 3.3.1. Thank you for reporting this issue!

**Comment by majora2007** [comment]
Thanks, btw, your release notes are wrong:
`EpubBook.Content.xxx.Local.ContainsKey(key) → EpubBook.Content.xxx.ContainsLocalFileWithKey(key);`

should be:
`EpubBook.Content.xxx.Local.ContainsKey(key) → EpubBook.Content.xxx.ContainsLocalFileRefWithKey(key);`

**Comment by vers-one** [comment]
Ah, sorry, it's `ContainsLocalFileWithKey` for `EpubBook.Content` and `ContainsLocalFileRefWithKey` for `EpubBookRef.Content`. I updated the release notes to clarify this point.
